spring:
  datasource:
    username: root
    password: dairui123
    url: jdbc:mysql://localhost:3306/sxwl?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  redis:
    password:
    host: localhost
    port: 6379
    database: 0
  mail:
    username: 754441650@qq.com
    password: qskqdmplfhrebebj
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
server:
  port: 8080
security:
  basic:
    enabled: false
